"""estrutura inicial

Revision ID: 869eea36026b
Revises: 
Create Date: 2026-10-03 17:55:26.293188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '869eea36026b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boletins_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('local', sa.Enum('INSUMOS', 'ADUBO', 'MAQUINAS', 'LOJA', name='localfisico', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'FECHADO', name='statusboletim', native_enum=False, length=30), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('producao_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('diarias_equivalentes', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('valor_por_diaria', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_pagar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('complemento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'local', name='uq_boletim_data_local')
    )
    op.create_index(op.f('ix_boletins_diarios_data'), 'boletins_diarios', ['data'], unique=False)
    op.create_table('chapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapas_matricula'), 'chapas', ['matricula'], unique=True)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_fornecedores_codigo'), 'fornecedores', ['codigo'], unique=True)
    op.create_table('tipos_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Enum('H08', 'H10', 'H13', 'H15', name='horario', native_enum=False, length=30), nullable=False),
    sa.Column('acondicionamento', sa.Enum('BATIDO', 'PALETIZADO', 'BIG_BAG', name='acondicionamento', native_enum=False, length=30), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('nf_arquivo_url', sa.String(), nullable=True),
    sa.Column('nf_numero', sa.String(length=20), nullable=True),
    sa.Column('nf_chave', sa.String(length=44), nullable=True),
    sa.Column('pedido_compra', sa.Integer(), nullable=True),
    sa.Column('analisado_por', sa.String(), nullable=True),
    sa.Column('analisado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacao_compras', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', 'CANCELADO', 'NA_FILA', 'EM_DESCARGA', 'CONCLUIDO', 'NAO_COMPARECEU', 'REAGENDADO', name='statusagendamento', native_enum=False, length=30), nullable=False),
    sa.Column('origem', sa.Enum('NORMAL', 'BALCAO', 'CHUVA', name='origemagendamento', native_enum=False, length=30), nullable=False),
    sa.Column('prioritario', sa.Boolean(), nullable=False),
    sa.Column('ciente_risco_chuva', sa.Boolean(), nullable=False),
    sa.Column('motivo_nao_recebimento', sa.Enum('SEM_VAGA', 'CHUVA', 'DIVERGENCIA_NF_PEDIDO', 'REJEITADO_COMPRAS', 'NAO_COMPARECEU', 'CANCELADO_FORNECEDOR', 'OUTRO', name='motivonaorecebimento', native_enum=False, length=30), nullable=True),
    sa.Column('reagendado_de_id', sa.Integer(), nullable=True),
    sa.Column('horario_chegada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['reagendado_de_id'], ['agendamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_data'), 'agendamentos', ['data'], unique=False)
    op.create_index(op.f('ix_agendamentos_fornecedor_id'), 'agendamentos', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_agendamentos_nf_chave'), 'agendamentos', ['nf_chave'], unique=False)
    op.create_index(op.f('ix_agendamentos_pedido_compra'), 'agendamentos', ['pedido_compra'], unique=False)
    op.create_index(op.f('ix_agendamentos_status'), 'agendamentos', ['status'], unique=False)
    op.create_table('boletim_chapas',
    sa.Column('boletim_id', sa.Integer(), nullable=False),
    sa.Column('chapa_id', sa.Integer(), nullable=False),
    sa.Column('meia_diaria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boletim_id'], ['boletins_diarios.id'], ),
    sa.ForeignKeyConstraint(['chapa_id'], ['chapas.id'], ),
    sa.PrimaryKeyConstraint('boletim_id', 'chapa_id')
    )
    op.create_table('boletim_producoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boletim_id', sa.Integer(), nullable=False),
    sa.Column('tipo_item_id', sa.Integer(), nullable=False),
    sa.Column('descarga', sa.Integer(), nullable=False),
    sa.Column('remocao', sa.Integer(), nullable=False),
    sa.Column('transferencia', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.CheckConstraint('descarga >= 0 AND remocao >= 0 AND transferencia >= 0', name='ck_producao_nao_negativa'),
    sa.ForeignKeyConstraint(['boletim_id'], ['boletins_diarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_item_id'], ['tipos_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boletim_id', 'tipo_item_id', name='uq_producao_boletim_tipo')
    )
    op.create_index(op.f('ix_boletim_producoes_boletim_id'), 'boletim_producoes', ['boletim_id'], unique=False)
    op.create_table('descargas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.Enum('INSUMOS', 'ADUBO', 'MAQUINAS', 'LOJA', name='localfisico', native_enum=False, length=30), nullable=False),
    sa.Column('horario_entrada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horario_saida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qtd_chapas', sa.Integer(), nullable=True),
    sa.Column('equipamentos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.CheckConstraint('horario_saida IS NULL OR horario_entrada IS NULL OR horario_saida >= horario_entrada', name='ck_descarga_tempos'),
    sa.CheckConstraint('qtd_chapas IS NULL OR qtd_chapas >= 0', name='ck_descarga_chapas'),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agendamento_id', 'local', name='uq_descarga_agendamento_local')
    )
    op.create_index(op.f('ix_descargas_agendamento_id'), 'descargas', ['agendamento_id'], unique=False)
    op.create_index(op.f('ix_descargas_local'), 'descargas', ['local'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_descargas_local'), table_name='descargas')
    op.drop_index(op.f('ix_descargas_agendamento_id'), table_name='descargas')
    op.drop_table('descargas')
    op.drop_index(op.f('ix_boletim_producoes_boletim_id'), table_name='boletim_producoes')
    op.drop_table('boletim_producoes')
    op.drop_table('boletim_chapas')
    op.drop_index(op.f('ix_agendamentos_status'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_pedido_compra'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_nf_chave'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_fornecedor_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_data'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_table('tipos_item')
    op.drop_index(op.f('ix_fornecedores_codigo'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_chapas_matricula'), table_name='chapas')
    op.drop_table('chapas')
    op.drop_index(op.f('ix_boletins_diarios_data'), table_name='boletins_diarios')
    op.drop_table('boletins_diarios')
    # ### end Alembic commands ###
